import Head from 'next/head';
import Image from 'next/image';
import React, { useEffect, useState } from 'react';
import { CasesApi } from '../api/CasesApi';
import { ProductsApi } from '../api/ProductsApi';
import { Advantages } from '../components/Advantages';
import { CaseOpeningSection } from '../components/CaseOpeningSection';
import { CasesListSection } from '../components/CasesListSection';
import { ProductsListSection } from '../components/ProductsListSection';
import { SliderSection } from '../components/SliderSection';
import { SettingsContextProvider } from '../contexts/SettingsContext';
import { containerTypes } from "../helpers";
import { Cases } from '../public/cases';

export default function Home({ products, orderedCasesItems, cases, casesItems }) {

  const [chosenContainerType, setChosenContainerType] = useState(containerTypes[0]);
  const [containerInfo, setContainerInfo] = useState({
    title: "Title",
    image: "Image",
  });
  const [items, setItems] = useState(null);
  const [specialItems, setSpecialItems] = useState(null);

  useEffect(() => {
    // const { title, image, items, specialItems } = Cases.find(
    //   (value) => value.id === 1 // +router.query.id
    // );



    setContainerInfo({
      title: 'title',
      image: 'image',
    });
    let newItems = casesItems.map(item => {
      return {
        id: item.id, title: item.title, image: item.photo, type: item.case, key: 'none'
      }
    });
    console.log(newItems)
    setItems(newItems);
    setSpecialItems(newItems.filter((item) => item.type === 3));
  }, [])

  return (
    <>
      <Head>
        <title>Главная страница 4keys</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SliderSection orders={orderedCasesItems} />
      <Advantages />
      <SettingsContextProvider>
        {chosenContainerType === containerTypes[0] &&
          items &&
          specialItems && (
            <CaseOpeningSection
              id="cases_open_section"
              items={items}
              containerType={containerTypes[0]}
              caseTitle={containerInfo.title}
              caseImage={containerInfo.image}
              specialItems={specialItems}
            />
          )}
      </SettingsContextProvider>
      <CasesListSection cases={cases} />
      <ProductsListSection products={products} />
    </>
  );
}

export async function getServerSideProps() {
  const products = await ProductsApi().getProducts(12);
  const cases = await CasesApi().getAll();
  const orderedCasesItems = await CasesApi().getCasesOrders();

  const casesItems = await CasesApi().getAllCasesItems() || [];
  let free = {
    id: 0,
    title: 'Бесплатный ключ',
    price: 0,
    created_at: new Date().toString(),
  };

  cases.unshift(free);

  if (!products?.data) {
    return {
      props: { products: { data: [] }, cases }, // will be passed to the page component as props
    }
  }

  if (!cases || !orderedCasesItems) {
    return {
      props: { products, cases, orderedCasesItems }, // will be passed to the page component as props
    }
  }

  return {
    props: { products, cases, orderedCasesItems, casesItems }, // will be passed to the page component as props
  }
}
