import Head from 'next/head';
import Image from 'next/image';
import React, { useEffect, useState } from 'react';
import { ProductsApi } from '../api/ProductsApi';
import { Advantages } from '../components/Advantages';
import { CaseOpeningSection } from '../components/CaseOpeningSection';
import { CasesListSection } from '../components/CasesListSection';
import { ProductsListSection } from '../components/ProductsListSection';
import { SliderSection } from '../components/SliderSection';
import { SettingsContextProvider } from '../contexts/SettingsContext';
import { containerTypes } from "../helpers";
import { Cases } from '../public/cases';

export default function Home({ products }) {

  const [chosenContainerType, setChosenContainerType] = useState(containerTypes[0]);
  const [containerInfo, setContainerInfo] = useState({
    title: "Title",
    image: "Image",
  });
  const [items, setItems] = useState(null);
  const [specialItems, setSpecialItems] = useState(null);

  useEffect(() => {
    const { title, image, items, specialItems } = Cases.find(
      (value) => value.id === 1 // +router.query.id
    );
    setContainerInfo({
      title,
      image,
    });
    setItems(items);
    setSpecialItems(specialItems);
  }, [])

  return (
    <>
      <Head>
        <title>Главная страница 4keys</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SliderSection />
      <Advantages />
      <SettingsContextProvider>
        {chosenContainerType === containerTypes[0] &&
          items &&
          specialItems && (
            <CaseOpeningSection
              items={items}
              containerType={containerTypes[0]}
              caseTitle={containerInfo.title}
              caseImage={containerInfo.image}
              specialItems={specialItems}
            />
          )}
      </SettingsContextProvider>
      <CasesListSection />
      <ProductsListSection products={products} />
    </>
  );
}

export async function getServerSideProps() {
  const products = await ProductsApi().getProducts(12);

  if (!products?.data) {
    return {
      props: { products: { data: [] } }, // will be passed to the page component as props
    }
  }

  return {
    props: { products }, // will be passed to the page component as props
  }
}
